
name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [node, python]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        if: matrix.language == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node dependencies
        if: matrix.language == 'node'
        run: npm install

      - name: Run Node tests
        if: matrix.language == 'node'
        run: npm test

      - name: Set up Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        if: matrix.language == 'python'
        run: pip install -r requirements.txt

      - name: Run Python tests
        if: matrix.language == 'python'
        run: pytest
